[tool.poetry]
name = "mlnode-pow"
version = "0.1.0"
description = "MLNode proof-of-work package"
authors = [
    "Gleb Morgachev <gleb.morgachev@productscience.ai>",
    "Tamaz Gadaev <tamaz@productscience.ai>",
    "Egor Shulgin <egor.shulgin@productscience.ai>"
]
packages = [{include = "pow", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.4.1"
pydantic = "^2.9.2"
scipy = "^1.14.1"
numpy = "^2.1.1"
tiktoken = "^0.8.0"
uvicorn = "^0.34.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
ruff = "^0.6.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
