version: "3.7"

services:
  node:
    container_name: node
    image: gcr.io/decentralized-ai/inferenced-join
    volumes:
      - .inference:/root/.inference
    env_file:
      - config.env
    ports:
      - "26656:26656" #p2p
      - "26657:26657" #rpc
  api:
    container_name: api
    image: gcr.io/decentralized-ai/api-join
    depends_on:
      - node
    environment:
      - KEY_NAME=${KEY_NAME}
    ports:
      - "8080:8080"
    # It shares the volume with the node, because it needs access to the keyring
    volumes:
      - .inference:/root/.inference
