services:
  chain-node:
    container_name: ${KEY_NAME}-node
    image: gcr.io/decentralized-ai/inferenced
    volumes:
      - ./prod-local/${KEY_NAME}:/root/.inference
    environment:
      - SEEDS=${SEEDS}
      - KEY_NAME=${KEY_NAME}
    networks:
      - chain-public

  api:
    container_name: ${KEY_NAME}-api
    image: gcr.io/decentralized-ai/api
    volumes:
      - ./prod-local/${KEY_NAME}:/root/.inference
    ports:
      - "${PORT}:8080"
    environment:
      - KEY_NAME=${KEY_NAME}
      - NODE_HOST=${KEY_NAME}-node
      - POC_CALLBACK_URL=${POC_CALLBACK_URL}
      - PUBLIC_URL=${PUBLIC_URL}
    networks:
      - chain-public

  wiremock:
    container_name: ${KEY_NAME}-wiremock
    image: "wiremock/wiremock:latest"
    ports:
      - "${WIREMOCK_PORT}:8080"
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
    networks:
      - chain-public

networks:
  chain-public:
    name: chain-public
