services:
  chain-node:
    container_name: ${KEY_NAME}-node
    image: inferenced-join
    volumes:
      - ./prod-local/${KEY_NAME}:/root/.inference
    environment:
      - SEEDS=${SEEDS}
      - KEY_NAME=${KEY_NAME}
    networks:
      - chain-public

  api:
    container_name: ${KEY_NAME}-api
    image: dapi-join
    volumes:
      - ./prod-local/${KEY_NAME}:/root/.inference
    ports:
      - "${PORT}:8080"
    environment:
      - KEY_NAME=${KEY_NAME}
      - NODE_HOST=${KEY_NAME}-node
      - POC_CALLBACK_HOST=${POC_CALLBACK_HOST}
    networks:
      - chain-public

  wiremock:
    container_name: ${KEY_NAME}-wiremock
    image: "wiremock/wiremock:latest"
    ports:
      - "${WIREMOCK_PORT}:8080"
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
    networks:
      - chain-public

networks:
  chain-public:
    name: chain-public
