services:
  genesis-node:
    image: gcr.io/decentralized-ai/inferenced
    container_name: genesis-node
    volumes:
      - ./prod-genesis:/root/.inference
    networks:
      - chain-public
    ports:
      - "26656:26656" #p2p
      - "26657:26657" #rpc

  genesis-api:
    image: gcr.io/decentralized-ai/api
    container_name: genesis-api
    volumes:
      - ./prod-genesis:/root/.inference
    ports:
      - "8080:8080"
    environment:
      - KEY_NAME=genesis
      - NODE_HOST=genesis-node
    networks:
      - chain-public

networks:
    chain-public:
        name: chain-public