version: "3.7"

services:
  chain-node:
    container_name: ${KEY_NAME}-node
    image: inferenced-join
    volumes:
      - ./prod-local/${KEY_NAME}:/root/.inference
    environment:
      - SEEDS=${SEEDS}
      - KEY_NAME=${KEY_NAME}
    networks:
      - net-public

  api:
    container_name: ${KEY_NAME}-api
    image: dapi-join
    volumes:
        - ./prod-local/${KEY_NAME}:/root/.inference
    ports:
      - "8089:8080"
    environment:
      - KEY_NAME=${KEY_NAME}
    networks:
      net-public:

networks:
  net-public:
