services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./resources:/app/resources:r
    environment:
      - MODEL_PARAMS_PATH=/app/resources/params.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      uvicorn pow.app:app
      --host=0.0.0.0
      --port=8080

  pow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:8080"
    volumes:
      - ./notebooks:/app/notebooks:Z
      - ./scripts:/app/scripts:Z
      - ./src:/app/src:Z
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    command: >
      jupyter-lab
      --ip=0.0.0.0
      --port=8080
      --no-browser
      --allow-root
      --notebook-dir /app/notebooks
      --NotebookApp.token=${JUPYTER_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart:
      always