version: '3.9'
services:
  web:
    image: httpd:latest
    container_name: binary-server
    ports:
      - '8781:80'
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/
    networks:
      - chain-public

networks:
  chain-public:
#    external: true
