services:
  pow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./notebooks:/app/notebooks:Z
      - ./scripts:/app/scripts:Z
    environment:
      - HOST_UID=${UID}
      - HOST_GID=${GID}
    command: >
      jupyter-lab
      --ip=0.0.0.0
      --port=8080
      --no-browser
      --notebook-dir /app/notebooks
      --NotebookApp.token=${JUPYTER_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart:
      always
    user: "${HOST_UID}:${HOST_GID}"
