x-common-config: &common-config
  env_file:
    - ${PROJECT_ROOT}/packages/train/.env
  network_mode: host
  shm_size: "120g"
  environment:
    - HF_TOKEN=${HF_TOKEN}
    - WANDB_API_KEY=${WANDB_API_KEY}
    - ZERO_BAND_LOG_LEVEL=DEBUG
  volumes:
    - /mnt/shared/cache:/root/.cache
    - ${PROJECT_ROOT}/packages/train/configs:/app/mlnode/packages/train/configs
    - ${PROJECT_ROOT}/packages/train/outputs:/app/mlnode/packages/train/outputs
    - ${PROJECT_ROOT}/packages/train/scripts:/app/mlnode/packages/train/scripts
    - ${PROJECT_ROOT}/packages/train/src:/app/mlnode/packages/train/src
    - ${PROJECT_ROOT}/packages/train/tests:/app/mlnode/packages/train/tests
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]
            device_ids: ["7"]

services:
  server:
    <<: *common-config
    image: train-test
    command: uvicorn zeroband.service.app:app --host=0.0.0.0 --port=8080

  train-api-test:
    <<: *common-config
    image: train-test
    working_dir: /app/mlnode/packages/train/tests
    command: python3 api_test.py

  shell:
    <<: *common-config
    image: train-test
    command: bash