name: Integration Tests

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk19-focal
      options: --user root

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Run Tests
        run: make run-tests

      - name: Archive Test Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: ./testermint/logs

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Tests
          path: ./testermint/build/test-results/**/*.xml
          reporter: java-junit
