name: Integration Tests

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  setup-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker (Latest Version)
        uses: docker/setup-docker-action@v4
        with:
          version: 'latest'

      - name: Verify Docker Installation
        run: |
          docker --version
          docker compose version

  integration-tests:
    needs: setup-docker
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk19-focal
      options: --user root --volume /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Verify Docker Installation
        run: |
          docker --version
          docker compose version
      - uses: actions/checkout@v3
      - name: Install Make
        run: |
          apt-get update
          apt-get install -y make
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Run Tests
        run: make run-tests

      - name: Archive Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: ./testermint/logs

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Tests
          path: ./testermint/build/test-results/**/*.xml
          reporter: java-junit
